#!/usr/bin/env node
// ABOUTME: Generates watch.js for the topo editor from the watch app: the renderer block of t.html (for the q display) and
// ABOUTME: the two parser stages ext1.js and ext9.js. Usage: node sync-watch.js [--check]; --check exits 1 when watch.js is stale.

'use strict';
const fs = require('fs');
const path = require('path');

const APP = path.resolve(__dirname, '../suuntopo_canvas');
const OUT = path.join(__dirname, 'watch.js');

function generate() {
  const html = fs.readFileSync(path.join(APP, 't.html'), 'utf8');
  const a = html.indexOf('  // BEGIN SHARED');
  const b = html.indexOf('  // END SHARED');
  if (a < 0 || b < 0) throw new Error('shared block markers missing in t.html');
  const shared = html.substring(a, b + '  // END SHARED'.length).replace(/{{\s*DISPLAY_ID\s*}}/g, 'q');
  if (/{{/.test(shared)) throw new Error('the shared block uses a token other than DISPLAY_ID');
  const stage = (f) => fs.readFileSync(path.join(APP, f), 'utf8').split('\n').filter((l) => !/^\/\/ ABOUTME:/.test(l)).join('\n').trim();
  // The camera calls of the template's paint(), Map first, then the whole topo, so the preview frames a topo like the watch.
  const fits = (html.match(/^ *fitRange\(.*\);$/gm) || []).map((l) => l.trim());
  if (fits.length !== 2) throw new Error('expected the two fitRange calls of paint() in t.html, found ' + fits.length);
  return [
    '// ABOUTME: Generated by sync-watch.js from src/suuntopo_canvas (t.html renderer block for display q, ext1.js and ext9.js); do not edit.',
    '// ABOUTME: Gives the topo editor the watch app\'s own renderer and parser as window.WATCH (parseTopo, show, drawTile, units).',
    'var WATCH = (function () {',
    shared,
    '',
    '  var STP1_STAGE1 = ' + stage('ext1.js') + ';',
    '',
    '  var STP1_STAGE2 = ' + stage('ext9.js') + ';',
    '',
    '  // Parses s like main.js does: stage 1 (header, text, pitches), then stage 2 (geometry into the stream words W).',
    '  var parseTopo = function (s, W, R) {',
    '    return STP1_STAGE1(s, R) || STP1_STAGE2(s, W, R);',
    '  };',
    '',
    '  // Editor adapter, mirroring t.html: take the stream words as if received, then pick the camera for drawing state ms',
    '  // (64 + idx Map, 128 + idx whole topo) the way the template\'s paint() does.',
    '  var show = function (W, nW, ms) {',
    '    var j, v, i = ms % 64, n;',
    '    for (j = 0; j < nW; j++) {',
    '      GB[3 * j] = Math.floor(W[j] / 65536);',
    '      GB[3 * j + 1] = Math.floor(W[j] / 256) % 256;',
    '      GB[3 * j + 2] = W[j] % 256;',
    '    }',
    '    v = wd(0);',
    '    nR = v % 128;',
    '    nB = Math.floor(v / 128) % 64;',
    '    nF = Math.floor(v / 8192);',
    '    oR = 2 + Math.ceil(nB / 3);',
    '    oF = oR + nR;',
    '    oP = oF + nF;',
    '    n = nB - 1;',
    '    ready = 2;',
    '    drawMode = ms < 64 ? 0 : 1;',
    '    hl = i;',
    '    if (ms < 128) {',
    '      ' + fits[0],
    '    } else {',
    '      ' + fits[1],
    '    }',
    '  };',
    '',
    '  return { parseTopo: parseTopo, show: show, drawTile: drawTile, units: function () { return units; }, skipped: function () { return skipped; } };',
    '})();',
    'if (typeof module !== \'undefined\' && module.exports) { module.exports = WATCH; }',
    ''
  ].join('\n');
}

if (require.main === module) {
  const text = generate();
  if (process.argv[2] === '--check') {
    const ok = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === text;
    console.log(ok ? 'watch.js is up to date' : 'watch.js is stale: run node src/topo_editor/sync-watch.js');
    process.exit(ok ? 0 : 1);
  }
  fs.writeFileSync(OUT, text);
  console.log('wrote ' + OUT);
}

module.exports = { generate, OUT };
