// ABOUTME: Generated by sync-watch.js from src/suuntopo_canvas (t.html renderer block for display q, ext1.js and ext9.js); do not edit.
// ABOUTME: Gives the topo editor the watch app's own renderer and parser as window.WATCH (parseTopo, show, drawTile, units).
var WATCH = (function () {
  // BEGIN SHARED
  // Geometry words, 3 bytes each: word 0 nR + nB*128 + nF*8192, word 1 point count, then stances (3 per word),
  // route points (x*4096+y), feature table (type*1024+count) and feature points.
  var GB = new Uint8Array(1932);
  var nR = 0, nB = 0, nF = 0, oR = 0, oF = 0, oP = 0;
  var wd = function (w) {
    w *= 3;
    return GB[w] * 65536 + GB[w + 1] * 256 + GB[w + 2];
  };
  // Route vertex index of stance i.
  var stance = function (i) {
    return Math.floor(wd(2 + Math.floor(i / 3)) / (i % 3 ? (i % 3 === 1 ? 128 : 16384) : 1)) % 128;
  };

  // Camera: world centre and zoom normalised to the 466 px display; fits route vertices i0..i1 into 0.8 of the width
  // and hmax px of height (0.54 of the display on the Map, so the target ring stays above #h1 at 80%; 0.43 on a list card
  // to leave the label line free).
  var camX = 0, camY = 0, camZ = 1, drawMode = 0, hl = -1, ready = 0;
  var fitRange = function (i0, i1, zlo, hmax) {
    var x0 = 4096, y0 = 4096, x1 = -1, y1 = -1, v, x, y;
    for (; i0 <= i1; i0++) {
      v = wd(oR + i0);
      x = Math.floor(v / 4096);
      y = v % 4096;
      x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y);
    }
    camZ = Math.max(zlo, Math.min(2, 372.8 / Math.max(x1 - x0, 40), hmax / Math.max(y1 - y0, 40)));
    camX = (x0 + x1) / 2;
    camY = (y0 + y1) / 2;
  };

  // Units the last tile drew and terrain features it left out (the editor preview shows both).
  var units = 0, skipped = 0;

  // The renderer: makeRenderer() returns drawTile(ctx, ti), which draws tile ti. Its constants, state and helpers live in
  // makeRenderer's scope, so neither that scope nor the template's reaches 56 names, where Duktape gives a scope record a
  // hash part (about 1.2 KB). makeRenderer runs once and is dropped with its prototype (a cycle refcounting cannot free).
  var makeRenderer = function () {
  var MIP = 'q' !== 'q';
  // Dim terrain (couloirs, slabs, contours, scree) keeps about 6:1 against black on q.
  var C_TER = MIP ? '#FFFFFF' : '#A6A6A6', C_DIM = MIP ? '#AAAAAA' : '#8A8A8A', C_GLY = MIP ? '#FFFFFF' : '#D9D9D9';
  var C_VEG = MIP ? '#55FF55' : '#6FA86F', C_NEXT = MIP ? '#FF0000' : '#FF5A36', C_CUR = MIP ? '#FFFF00' : '#FFD400';
  // Done pitches keep at least 3:1 against black; walks (approach, descent) use a blue no terrain uses.
  var C_DONE = MIP ? '#AA5555' : '#B05A48', C_WALK = MIP ? '#55AAFF' : '#5AC8FA';
  var TILE_CAP = 150, TILE_TOP = [0.16, 0.39, 0.62];
  // Point glyphs of b n v x t w z: M move, L line; digits 0-8 map to -1..1 of the glyph size.
  var GLYPH = ['M00L88M80L08', 'M20L26L86', 'M02L82L48L02', 'M40L74L48L14L40', 'M48L44L10M44L70', 'M26L02M46L41M66L82', 'M00L88M80L08'];
  var FPRI = '1111111223442222334';

  // Pen with budget: units = 2 per stroke, 1 per moveTo or lineTo. A path is stroked at 20 ops, and an op that would take
  // the tile past TILE_CAP is dropped, so a tile never goes black. Frames draw no arc and no fill (their Race S cost is
  // unmeasured); the only other call is the background fillRect, counted as 2 units in drawTile.
  var gx = null, dry = 0, pOps = 0, pCol = '', pW = 0, lastX = 0, lastY = 0, steps = 0;
  var sz = 1, ox = 0, oy = 0, tW = 0, tH = 0, mg = 0, kd = 1, kw = 1, dec = 3, cX = 0, cY = 0, cOpen = 0, PX = 0, PY = 0;
  var flush = function () {
    if (pOps) {
      units += 2;
      if (!dry) { gx.stroke(); }
    }
    pOps = 0;
  };
  var pen = function (col, w) {
    w = w * kw;
    if (col !== pCol || w !== pW) {
      flush();
      pCol = col;
      pW = w;
      if (!dry) { gx.strokeStyle = col; gx.lineWidth = w; }
    }
  };
  // moveTo (line 0) or lineTo (line 1) on the open path.
  var op = function (x, y, line) {
    if (pOps >= 20) {
      flush();
      if (line) { op(lastX, lastY, 0); }
    }
    if (units + 3 > TILE_CAP) { return; }
    if (!pOps && !dry) { gx.beginPath(); }
    pOps++;
    units++;
    if (!dry) {
      if (line) { gx.lineTo(x, y); } else { gx.moveTo(x, y); }
    }
    lastX = x;
    lastY = y;
  };
  // Dry-runs fn(a, b, c) into a fresh path and returns its unit cost.
  var costOf = function (fn, a, b, c) {
    var sU = units, sO = pOps, sC = pCol, sWd = pW, sX = lastX, sY = lastY;
    dry = 1;
    units = 0;
    pOps = 0;
    pCol = '';
    fn(a, b, c);
    flush();
    a = units;
    dry = 0;
    units = sU; pOps = sO; pCol = sC; pW = sWd; lastX = sX; lastY = sY;
    return a;
  };
  var vis = function (x0, y0, x1, y1) {
    return !((x0 > x1 ? x0 : x1) < -mg || (x0 < x1 ? x0 : x1) > tW + mg || (y0 > y1 ? y0 : y1) < -mg || (y0 < y1 ? y0 : y1) > tH + mg);
  };
  // Screen position of geometry word w into PX, PY.
  var pt = function (w) {
    w = wd(w);
    PX = Math.floor(w / 4096) * sz + ox;
    PY = (w % 4096) * sz + oy;
  };
  // Clipping polyline from (cX, cY): draws to (x, y) only where the segment nears the tile.
  var cTo = function (x, y) {
    if (vis(cX, cY, x, y)) {
      if (!cOpen) { op(cX, cY, 0); cOpen = 1; }
      op(x, y, 1);
    } else {
      cOpen = 0;
    }
    cX = x;
    cY = y;
  };

  // Route vertices i0..i1, dropping vertices closer than dec px to the last one kept.
  var drawRun = function (i0, i1, col, w) {
    if (i1 <= i0) { return; }
    pen(col, w);
    pt(oR + i0);
    cX = PX; cY = PY; cOpen = 0;
    while (i0 < i1) {
      pt(oR + ++i0);
      if (i0 === i1 || (PX - cX) * (PX - cX) + (PY - cY) * (PY - cY) >= dec * dec * kd * kd) { cTo(PX, PY); }
    }
  };
  // Route by importance: current pitch, upcoming, done, then walks; under budget pressure the tail is what drops.
  // The walk of the position (approach at Start, descent at Top) is drawn wide.
  var drawRoute = function () {
    var n = nB - 1, b0 = stance(0), bn = stance(n);
    if (hl < 0) {
      drawRun(b0, bn, C_NEXT, 5);
    } else {
      if (hl >= 1 && hl <= n) { drawRun(stance(hl - 1), stance(hl), C_CUR, 7); }
      if (hl <= n) { drawRun(stance(hl), bn, C_NEXT, 5); }
      if (hl > 1) { drawRun(b0, stance(Math.min(hl, n + 1) - 1), C_DONE, 4); }
    }
    drawRun(bn, nR - 1, C_WALK, hl > n ? 5 : 2.5);
    drawRun(0, b0, C_WALK, hl ? 2.5 : 5);
  };
  // Stances as white dots (1 px segments in one path, round caps set per tile: 2 units each, as arc costs are unmeasured on the
  // watch), smaller when zoomed out so a long route stays visible; then the target stance ringed: a 20 px white dot under a
  // 14 px yellow one, each its own path (8 units).
  var drawBelays = function () {
    var i, n = nB - 1, tg = hl < 0 ? -1 : Math.min(hl, n), r = Math.max(2.5, Math.min(6, camZ * 10));
    pen('#FFFFFF', 2 * r);
    for (i = 0; i <= n; i++) {
      pt(oR + stance(i));
      if (i !== tg && vis(PX, PY, PX, PY)) {
        op(PX, PY, 0);
        op(PX + 1, PY, 1);
      }
    }
    pt(oR + stance(Math.max(tg, 0)));
    if (tg >= 0 && vis(PX, PY, PX, PY)) {
      pen('#FFFFFF', 20);
      op(PX, PY, 0);
      op(PX + 1, PY, 1);
      pen(C_CUR, 14);
      op(PX, PY, 0);
      op(PX + 1, PY, 1);
    }
    flush();
  };

  // Point feature type t (12-18): one glyph per point.
  var drawGlyphs = function (t, np, po) {
    var g = GLYPH[t - 12], h = (t === 18 ? 4 : 8) * kd, i, j;
    pen(t === 16 || t === 17 ? C_VEG : (t === 18 ? C_DIM : C_GLY), t === 18 ? 1.5 : 2.5);
    for (i = 0; i < np; i++) {
      pt(po + i);
      if (vis(PX - h, PY - h, PX + h, PY + h)) {
        for (j = 0; j < g.length; j += 3) {
          op(PX + (g.charCodeAt(j + 1) - 52) * h / 4, PY + (g.charCodeAt(j + 2) - 52) * h / 4, g.charAt(j) === 'L');
        }
      }
    }
  };
  // Line feature type t (0-10): plain, ticks (roof, overhang, ramp), zig-zag (crack), double (chimney, corner, gully)
  // or closed (slab). Decorations become plain lines below zoom 0.6. Zig-zag and ticks step along the whole segment, so they
  // are drawn (dd) only on a segment that nears the tile and is at most two tile widths long on screen; a longer one draws
  // plain. A segment whose bounding box nears the tile while its line misses it costs steps but no budget units, so the
  // patterned length is also capped per tile (steps, 8,000 px at 466 px width, dry runs included); past the cap segments
  // draw plain. The feature stops once the tile budget is spent. Together these bound the work per frame (SPEC §7).
  var drawLine = function (t, np, po) {
    var deco = camZ >= 0.6, i, j, x0, y0, len, ux, uy, s = 0, h, n, dd, e;
    pen(t > 7 ? C_DIM : (t === 6 ? C_GLY : C_TER), t === 2 ? 5 : (t === 10 ? 1.5 : (t === 6 ? 3 : 2.5)));
    if (t === 4 || t === 5 || t === 8) { s = (t === 4 ? 5 : (t === 5 ? 2.5 : 6)) * kd; }
    pt(po);
    cX = PX; cY = PY; cOpen = 0;
    for (i = 1; (i < np || (t === 9 && i === np && np > 2)) && units + 3 <= TILE_CAP; i++) {
      x0 = cX;
      y0 = cY;
      pt(po + i % np);
      len = Math.sqrt((PX - x0) * (PX - x0) + (PY - y0) * (PY - y0));
      if (len < 0.5) { continue; }
      ux = (PX - x0) / len;
      uy = (PY - y0) / len;
      // dd: this segment gets its zig-zag (3) or ticks (0, 1, 7).
      dd = deco && (t === 3 || t < 2 || t === 7) && len <= 2 * tW && vis(x0, y0, PX, PY) && (steps += len / kd) <= 8000;
      if (s && deco) {
        if (vis(x0, y0, PX, PY)) {
          op(x0 - uy * s, y0 + ux * s, 0); op(PX - uy * s, PY + ux * s, 1);
          op(x0 + uy * s, y0 - ux * s, 0); op(PX + uy * s, PY - ux * s, 1);
        }
        cX = PX; cY = PY; cOpen = 0;
        continue;
      }
      n = Math.max(2, Math.round(len / (4 * kd)));
      for (j = 1; t === 3 && dd && j < n; j++) {
        h = (j % 2 ? 3 : -3) * kd;
        cTo(x0 + ux * len * j / n - uy * h, y0 + uy * len * j / n + ux * h);
      }
      cTo(PX, PY);
      if (dd && t !== 3) {
        h = (t === 0 ? 8 : (t === 1 ? 14 : 10)) * kd;
        n = Math.floor(len / h);
        for (j = 0; j <= n; j++) {
          // Tick j sits e px back from the end of the segment; the ticks are centred along it.
          e = len - (len - n * h) / 2 - h * j;
          x0 = PX - ux * e;
          y0 = PY - uy * e;
          if (vis(x0, y0, x0, y0)) {
            op(x0, y0, 0);
            if (t === 7) { op(x0 + (ux - uy) * 5 * kd, y0 + (uy + ux) * 5 * kd, 1); } else { op(x0 - uy * (t ? 9 : 6) * kd, y0 + ux * (t ? 9 : 6) * kd, 1); }
          }
        }
        cOpen = 0;
      }
    }
  };

  // Every function gets an automatic prototype object (about 50 B); none of these helpers is a constructor.
  flush.prototype = pen.prototype = op.prototype = costOf.prototype = vis.prototype = pt.prototype = cTo.prototype = null;
  drawRun.prototype = drawRoute.prototype = drawBelays.prototype = drawGlyphs.prototype = drawLine.prototype = null;

  // Draws tile ti (0-2): terrain by priority in what the route and stances leave of the budget, then route and stances.
  return function (ctx, ti) {
    var W = ctx.width, k = W / 466, budget, pr, f, v, t, po, c, fn;
    gx = ctx;
    dry = 0;
    pOps = 0;
    pCol = '';
    units = 2;
    skipped = 0;
    steps = 0;
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, W, ctx.height);
    ctx.lineCap = 'round';
    if (!drawMode || !ready) { return units; }
    tW = W; tH = ctx.height; mg = 12 * k; kd = k; kw = Math.max(k, 0.6);
    sz = camZ * k; ox = W / 2 - camX * sz; oy = W / 2 - camY * sz - Math.round(W * TILE_TOP[ti]);
    dec = camZ < 0.6 ? 6 : 3;
    budget = TILE_CAP - 2 - costOf(drawRoute) - costOf(drawBelays);
    for (pr = 1; pr <= 4 && ready > 1; pr++) {
      for (f = 0, po = oP; f < nF; f++) {
        v = wd(oF + f);
        t = Math.floor(v / 1024);
        fn = t < 12 ? drawLine : drawGlyphs;
        if (FPRI.charCodeAt(t) - 48 === pr && t !== 11 && (t < 12 || camZ >= 0.6)) {
          c = costOf(fn, t, v % 1024, po);
          if (c && c + 3 <= budget) {
            budget -= c + 3;
            fn(t, v % 1024, po);
          } else if (c) {
            skipped++;
          }
        }
        po += v % 1024;
      }
    }
    flush();
    pCol = '';
    drawRoute();
    flush();
    drawBelays();
    return units;
  };
  };
  var drawTile = makeRenderer();
  makeRenderer.prototype = null;
  makeRenderer = null;
  // END SHARED

  var STP1_STAGE1 = function (s, R) {
  var L, p = 4, a, e, t, k, q, x, d, nP = 0, h = 0, seen = 0, c = 0, bad;
  R[0] = 1;
  if (typeof s !== 'string') { return 1; }
  L = s.length;
  if (L < 4 || s.substring(0, 4) !== 'STP1' || (L > 4 && s.charCodeAt(4) !== 124)) { return 1; }
  for (k = 0; k < L; k++) { h = (h + s.charCodeAt(k) * (k % 31 + 1)) % 65521; }
  R[0] = 7;
  if (L > 3500) { return 7; }
  // 1 when the text between a and e is longer than max characters or holds a control character, '<' or '&': setText reads
  // markup and character entities, so a name like 'A <b>B</b>' or 'A &amp; B' would not show as written.
  bad = function (a, e, max) {
    var ch;
    if (e - a > max) { return 1; }
    for (; a < e; a++) {
      ch = s.charCodeAt(a);
      if (ch < 32 || ch === 60 || ch === 38) { return 1; }
    }
    return 0;
  };
  for (k = 4; k < 12; k++) { R[k] = 0; }
  while (p < L) {
    a = p + 1;
    e = s.indexOf('|', a);
    if (e < 0) { e = L; }
    t = s.charAt(a++);
    c = 0;
    if (t === 'N') {
      c = seen || e === a || bad(a, e, 32) ? 2 : 0;
      seen = 1; R[4] = a; R[5] = e;
    } else if (t === 'W' || t === 'G' || t === 'A' || t === 'D') {
      c = bad(a, e, t === 'G' ? 10 : (t === 'W' ? 32 : 200)) ? 7 : 0;
      k = 'xxGxAxD'.indexOf(t) + 4;
      if (k > 4) { R[k] = a; R[k + 1] = e; }
    } else if (t === 'P') {
      // band~grade~len~info: pitch table entry band*1000+len, gradeStart*256+gradeLen, infoStart*256+infoLen.
      k = s.charCodeAt(a) - 48;
      q = s.indexOf('~', a + 2);
      x = 0;
      for (d = q + 1; s.charCodeAt(d) >= 48 && s.charCodeAt(d) <= 57; d++) { x = x * 10 + s.charCodeAt(d) - 48; }
      if (!(k >= 0 && k <= 4) || s.charAt(a + 1) !== '~' || q < 0 || q >= e || bad(a + 2, q, 10) || d - q < 2 || d - q > 4 || s.charAt(d) !== '~' || d >= e || bad(d + 1, e, 200) || nP > 59) {
        c = 5;
      } else {
        R[16 + 3 * nP] = k * 1000 + x;
        R[17 + 3 * nP] = (a + 2) * 256 + q - a - 2;
        R[18 + 3 * nP++] = (d + 1) * 256 + e - d - 1;
      }
    }
    if (c) { break; }
    p = e;
  }
  // bad and this call's scope refer to each other (and bad to its automatic prototype), which reference counting cannot
  // free: drop the links so a parse leaves no cyclic garbage (SPEC §8).
  bad.prototype = null;
  bad = null;
  if (c) { R[0] = c; return c; }
  R[0] = seen ? 0 : 2;
  R[1] = nP;
  R[2] = h || 1;
  return R[0];
};

  var STP1_STAGE2 = function (s, W, R) {
  var L = s.length, p = 4, a, e, t, k, c = 0, q, x, y, last = -1, seen = 0, pp, pv;
  var nR = 0, nB = 0, nF = 0, nFP = 0, nFR = 0;
  // Reads an integer of 1-4 digits with an optional minus at pp into pv.
  var num = function () {
    var d = 0, neg = s.charAt(pp) === '-';
    pv = 0;
    if (neg) { pp++; }
    while (s.charCodeAt(pp) >= 48 && s.charCodeAt(pp) <= 57) { pv = pv * 10 + s.charCodeAt(pp++) - 48; d++; }
    if (neg) { pv = -pv; }
    return d > 0 && d < 5;
  };
  // Reads x,y[,dx,dy]* between a and e into W from word o as x*4096+y. Returns the count, -1 on a syntax or range
  // error, -2 when there are more than max points.
  var path = function (a, e, o, max) {
    var n = 0;
    pp = a;
    for (;;) {
      if (!num()) { return -1; }
      x = n ? x + pv : pv;
      if (s.charAt(pp++) !== ',' || !num()) { return -1; }
      y = n ? y + pv : pv;
      if (x < 0 || x > 4095 || y < 0 || y > 4095) { return -1; }
      if (n >= max) { return -2; }
      W[o + n++] = x * 4096 + y;
      if (pp === e) { return n; }
      if (s.charAt(pp++) !== ',') { return -1; }
    }
  };
  // Regions at their largest offsets, compacted at the end: stances 2, route 23, feature table 143, points 243.
  while (p < L) {
    a = p + 1;
    e = s.indexOf('|', a);
    if (e < 0) { e = L; }
    t = s.charAt(a++);
    c = 0;
    if (t === 'R') {
      k = path(a, e, 23, 120);
      c = seen & 1 ? 3 : (k === -1 ? 6 : (k < 2 ? 3 : 0));
      seen |= 1;
      nR = k;
    } else if (t === 'B') {
      c = seen & 2 ? 4 : 0;
      seen |= 2;
      pp = a;
      while (!c) {
        if (!num()) { c = 6; } else if (pv <= last || nB > 60) { c = 4; } else {
          k = 2 + Math.floor(nB / 3);
          W[k] = (nB % 3 ? W[k] : 0) + pv * (nB % 3 ? (nB % 3 === 1 ? 128 : 16384) : 1);
          last = pv;
          nB++;
          if (pp === e) { break; }
          if (s.charAt(pp++) !== ',') { c = 6; }
        }
      }
      if (!c && nB < 2) { c = 4; }
    } else if (t === 'F') {
      t = 'rolkhdapgscqbnvxtwz'.indexOf(s.charAt(a++));
      c = t >= 0 && ++nFR > 40 ? 7 : 0;
      while (t >= 0 && !c) {
        q = s.indexOf(';', a);
        if (q < 0 || q > e) { q = e; }
        k = path(a, q, 243 + nFP, 400 - nFP);
        if (k < 0 || nF > 99) { c = k === -1 ? 6 : 7; } else {
          W[143 + nF++] = t * 1024 + k;
          nFP += k;
          if (q === e) { break; }
          a = q + 1;
        }
      }
    }
    if (c) { break; }
    p = e;
  }
  // The helpers and this call's scope refer to each other (and each helper to its automatic prototype), which reference
  // counting cannot free: drop the links so a parse leaves no cyclic garbage (SPEC §8).
  num.prototype = path.prototype = null;
  num = path = null;
  c = c || (!(seen & 1) ? 3 : (!(seen & 2) || last >= nR ? 4 : (R[1] !== nB - 1 ? 5 : 0)));
  R[0] = c;
  if (c) { return c; }
  // Compact: header, stances, route, feature table, points.
  W[0] = nR + nB * 128 + nF * 8192;
  W[1] = nFP;
  q = 2 + Math.ceil(nB / 3);
  for (k = 0; k < nR + nF + nFP; k++) { W[q + k] = W[k < nR ? 23 + k : (k < nR + nF ? 143 + k - nR : 243 + k - nR - nF)]; }
  R[3] = q + nR + nF + nFP;
  return 0;
};

  // Parses s like main.js does: stage 1 (header, text, pitches), then stage 2 (geometry into the stream words W).
  var parseTopo = function (s, W, R) {
    return STP1_STAGE1(s, R) || STP1_STAGE2(s, W, R);
  };

  // Editor adapter, mirroring t.html: take the stream words as if received, then pick the camera for drawing state ms
  // (64 + idx Map, 128 + idx whole topo) the way the template's paint() does.
  var show = function (W, nW, ms) {
    var j, v, i = ms % 64, n;
    for (j = 0; j < nW; j++) {
      GB[3 * j] = Math.floor(W[j] / 65536);
      GB[3 * j + 1] = Math.floor(W[j] / 256) % 256;
      GB[3 * j + 2] = W[j] % 256;
    }
    v = wd(0);
    nR = v % 128;
    nB = Math.floor(v / 128) % 64;
    nF = Math.floor(v / 8192);
    oR = 2 + Math.ceil(nB / 3);
    oF = oR + nR;
    oP = oF + nF;
    n = nB - 1;
    ready = 2;
    drawMode = ms < 64 ? 0 : 1;
    hl = i;
    if (ms < 128) {
      fitRange(i < 1 ? 0 : stance(Math.min(i, n) - 1), i > n ? nR - 1 : stance(Math.max(Math.min(i, n), 1)), 0.35, 250);
    } else {
      fitRange(0, nR - 1, 0.045, 200);
    }
  };

  return { parseTopo: parseTopo, show: show, drawTile: drawTile, units: function () { return units; }, skipped: function () { return skipped; } };
})();
if (typeof module !== 'undefined' && module.exports) { module.exports = WATCH; }
